### ISSUE TITLE
Error on Swapping Desktops

### ISSUE THREAD

**Issue by ghost** [ViRb3/SylphyHornEx#21]
I'm unable to swap desktops after latest windows update.

I'm on Windows 10 v20H2 build 19042.610

This is the error I get:
```
System.ArgumentException: Value is not within expected range.
   at WindowsDesktop.Interop.ComInterfaceWrapperBase.Invoke[T](Object[] parameters, String methodName) in D:\a\SylphyHornEx\SylphyHornEx\source\VirtualDesktop\source\VirtualDesktop\Interop\ComInterfaceWrapperBase.cs:line 60
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal.MoveViewToDesktop(ApplicationView pView, VirtualDesktop desktop) in D:\a\SylphyHornEx\SylphyHornEx\source\VirtualDesktop\source\VirtualDesktop\Interop\(wrappers)\VirtualDesktopManagerInternal.cs:line 18
   at WindowsDesktop.VirtualDesktopHelper.MoveToDesktop(IntPtr hWnd, VirtualDesktop virtualDesktop) in D:\a\SylphyHornEx\SylphyHornEx\source\VirtualDesktop\source\VirtualDesktop\VirtualDesktopHelper.cs:line 52
   at SylphyHorn.Services.VirtualDesktopMoveService.SwapDesktops(VirtualDesktop source, VirtualDesktop target) in D:\a\SylphyHornEx\SylphyHornEx\source\SylphyHorn\Services\VirtualDesktopMoveService.cs:line 45
   at SylphyHorn.Services.VirtualDesktopMoveService.MoveLeft() in D:\a\SylphyHornEx\SylphyHornEx\source\SylphyHorn\Services\VirtualDesktopMoveService.cs:line 20
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by ghost** [comment]
Nevermind...seems like a reboot fixed it

**Comment by ghost** [comment]
Seems like I have to reopen this issue, it's still an issue and happens quire regularly.
