### ISSUE TITLE
Error on Swapping Desktops

### ISSUE THREAD

**Issue by Snuupy** [ViRb3/SylphyHornEx#9]
Hi,

I'm unable to swap desktops. I'm using the shortcut LeftWin + LeftAlt + LeftArrow|RightArrow but I've tried other ones as well.

I'm on Windows 10 v2004 build 19041.264.

This is the error I get:

```
System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at SylphyHorn.UI.Controls.UnlockImageConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in D:\a\SylphyHornEx\SylphyHornEx\source\SylphyHorn\UI\Controls\UnlockImageConverter.cs:line 22
```

Please let me know if there's any other information that would be useful that I'd be able to provide.

**Comment by ViRb3** [comment]
Hello and sorry for the late response.
Those exceptions are not functionally critical, I get them as well and everything is working. I admit that they should be fixed, I will keep this open as a reminder to do so.
The shortcut to switch desktops is `LCtrl` + `LWin` + `Left/Right arrow`, no `LAlt` included. Could you try those and let me know?
Thanks

**Comment by Snuupy** [comment]
Hey - no worries, thanks for improving this project!

On latest release LCtrl+LWin+Left/Right arrow works.

**Comment by Snuupy** [comment]
> The shortcut to switch desktops is `LCtrl` + `LWin` + `Left/Right arrow`, no `LAlt` included. Could you try those and let me know?

Sorry, to swap desktops. `LCtrl + LShift + LWin` + `Left/Right` doesn't work. Windows overwrites the shortcut and thinks you're trying to snap the screen to the left or right side.

Using other shortcuts (such as `LShift + LAlt` + `Left/Right`) doesn't seem to do anything.
